app:
  host: localhost
  port: 9000
  url: http://localhost:9000
  debug: true

database:
  db_name: db/finance.db
  db_type: sqlite
  timeout_second: 30

core:
  logger:
    level: INFO
    filename: server.log
  bugger:
    filename: bugs.log

api:
  time_to_update_second: 86400

test:
  mock_boolean: true
  mock_string: test_finance.db
  mock_integer: 42
  mock_float: 3.14
