app:
  host: localhost
  port: 5000
  url: http://localhost:5000
  debug: true

database:
  db_name: finance.db
  db_type: sqlite
  timeout_second: 30

api:
  time_to_update_second: 86400

test:
  mock_boolean: true
  mock_string: test_finance.db
  mock_integer: 42
  mock_float: 3.14
